language: cpp

os: linux

cache:
  - apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --yes libmysqlclient-dev
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq --yes gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  # DBMS Settings
  - mysql -e "CREATE USER 'ci_environment'@'localhost' IDENTIFIED BY 'abc12345'; GRANT ALL ON *.* TO 'ci_environment'@'localhost'";

install:
  - if [ -e /usr/share/ant/lib/ant-jsch.jar ]; then sudo rm /usr/share/ant/lib/ant-jsch.jar -qq; fi
  - ant -propertyfile ci.properties create_schema
  - ant -propertyfile ci.properties init_schema

services:
  - mysql

dist: trusty
sudo: enabled

notifications:
    email:
      on_success: never  # default: change
      on_failure: always # default: always
