language: cpp

os: linux

dist: xenial
sudo: enabled

cache:
  - apt

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --yes libmysqlclient-dev
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install gcc-snapshot --yes
  - sudo apt-get install gcc-6 g++-6 --yes
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

install:
  # It makes available CMake 3.7.2
  - sudo wget https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz
  - tar -xf cmake-3.7.2.tar.gz
  - cd cmake-3.7.2
  - sudo ./configure
  - sudo make && sudo make install

  # It makes available Google Test
  - sudo sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib

  # It makes available Poco 1.8.1
  - sudo wget https://pocoproject.org/releases/poco-1.8.1/poco-1.8.1-all.tar.gz
  - sudo tar -xf poco-1.8.1-all.tar.gz
  - cd poco-1.8.1-all
  - sudo ./configure --no-tests --no-samples --everything --omit=MongoDB,Data/ODBC,PDF,CppParser,Crypto,NetSSL_OpenSSL,CppUnit,PageCompiler
  - sudo make && sudo make install

services:
  - mysql

notifications:
    email:
      on_success: never  # default: change
      on_failure: always # default: always

before_script:
  # =============================================================
  # It makes available a MySQL User with proper privileges to
  # perform database tests.
  # =============================================================
  - mysql -e "CREATE USER 'ci_environment'@'localhost' IDENTIFIED BY 'abc12345'; GRANT ALL ON *.* TO 'ci_environment'@'localhost'";

  # It removes standard Ant Jsch package for using the local one.
  - if [ -e "/usr/share/ant/lib/ant-jsch.jar" ]; then
      sudo rm "/usr/share/ant/lib/ant-jsch.jar"; fi

  # =============================================================
  # The following Ant Tasks:
  #  1. Create the database
  #  2. Create DBDeploy and Application tables as well as load
  #  sample data.
  # =============================================================
  - cd $TRAVIS_BUILD_DIR
  - ant -propertyfile ci.properties create_schema
  - ant -propertyfile ci.properties init_schema

script:
  - sudo mkdir cmake-build && cd cmake-build
  - sudo cmake $TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Default -DENABLE_TESTS=no -DENABLE_STANDALONE_SERVICE=no
  - sudo cmake --build . --target all -- -j 2

after_script:
  # =============================================================
  # The following Ant Task destroys database and all sample data.
  # =============================================================
  - cd $TRAVIS_BUILD_DIR
  - ant -propertyfile ci.properties drop_schema
